//! Прогон настоящего бинарника по временному «/etc/hosts».
//!
//! Проверяем главное обещание утилиты: всё, что вне маркеров, остаётся на месте.

mod common;
use common::{SYSTEM_HEAD, Sandbox, assert_system_lines_intact, bin};
use std::path::Path;
use std::process::Command;

#[test]
fn full_lifecycle_keeps_system_lines() {
    let s = Sandbox::new();
    s.init();

    s.ok(&["add", "127.0.0.1", "k8s.orb.local", "--comment", "orbstack"]);
    s.ok(&["add", "10.30.13.37", "sre-mcp.local"]);
    s.ok(&["apply", "-y"]);

    let hosts = s.hosts();
    assert_system_lines_intact(&hosts);
    assert!(hosts.contains("k8s.orb.local"));
    assert!(hosts.contains("sre-mcp.local"));
    assert!(hosts.contains("# >>> hostsctl begin >>>"));

    // Повторный apply идемпотентен по содержимому блока.
    s.ok(&["apply", "-y"]);
    let again = s.hosts();
    assert_eq!(again.matches("# >>> hostsctl begin >>>").count(), 1, "the block was duplicated");

    // disable убирает запись из файла, но не из конфига
    s.ok(&["disable", "sre-mcp.local"]);
    s.ok(&["apply", "-y"]);
    let hosts = s.hosts();
    assert!(!hosts.contains("sre-mcp.local"));
    assert!(s.ok(&["list", "--all"]).contains("sre-mcp.local"));
    assert_system_lines_intact(&hosts);

    // off убирает блок целиком, файл возвращается к исходному виду
    s.ok(&["off", "-y"]);
    let hosts = s.hosts();
    assert!(!hosts.contains("hostsctl begin"));
    assert!(!hosts.contains("k8s.orb.local"));
    assert_system_lines_intact(&hosts);
}

#[test]
fn manual_edits_outside_block_survive_apply() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "app.local"]);
    s.ok(&["apply", "-y"]);

    // Пользователь дописал строку руками уже после apply.
    let mut hosts = s.hosts();
    hosts.push_str("\n# added by hand\n192.168.1.10 printer.home\n");
    std::fs::write(s.target(), &hosts).unwrap();

    s.ok(&["add", "127.0.0.1", "api.local"]);
    s.ok(&["apply", "-y"]);

    let after = s.hosts();
    assert!(after.contains("192.168.1.10 printer.home"));
    assert!(after.contains("# added by hand"));
    assert!(after.contains("api.local"));
    assert_system_lines_intact(&after);
}

#[test]
fn stale_timestamp_alone_is_not_drift() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "stable.local"]);
    s.ok(&["apply", "-y"]);

    // Отматываем отметку времени назад — как будто apply был вчера.
    let hosts = s.hosts();
    let old = hosts
        .lines()
        .map(|l| {
            if l.starts_with("# generated by hostsctl ") {
                "# generated by hostsctl 2020-01-01 00:00".to_string()
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    std::fs::write(s.target(), &old).unwrap();

    assert!(s.ok(&["diff"]).contains("no changes"), "diff sees drift that is not there");
    assert!(s.ok(&["status"]).contains("matches the config"));
    s.ok(&["apply", "-y"]);
    assert_eq!(s.hosts(), old, "apply rewrote the file for no reason");

    // А настоящее изменение отметку обновляет.
    s.ok(&["add", "127.0.0.1", "fresh.local", "--apply"]);
    assert!(!s.hosts().contains("2020-01-01"));
}

#[test]
fn dry_run_writes_nothing() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "dry.local"]);
    let before = s.hosts();
    let out = s.ok(&["apply", "-y", "-n"]);
    assert!(out.contains("dry-run"));
    assert_eq!(before, s.hosts());
}

#[test]
fn backup_and_restore_roundtrip() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "one.local"]);
    s.ok(&["apply", "-y"]);
    let with_one = s.hosts();

    s.ok(&["add", "127.0.0.1", "two.local"]);
    s.ok(&["apply", "-y"]);
    assert!(s.hosts().contains("two.local"));

    let list = s.ok(&["backup", "list"]);
    assert!(list.lines().count() >= 2, "too few backups:\n{list}");

    s.ok(&["backup", "restore", "-y"]);
    assert_eq!(s.hosts(), with_one, "the restore did not bring the previous state back");
}

#[test]
fn legacy_hosts_sync_block_is_left_alone() {
    let s = Sandbox::new();
    let legacy = format!(
        "{SYSTEM_HEAD}\n# >>> hosts-sync begin >>>\n127.0.0.1 legacy.local\n# <<< hosts-sync end <<<\n"
    );
    std::fs::write(s.target(), &legacy).unwrap();
    s.init();
    s.ok(&["add", "127.0.0.1", "new.local"]);

    let out = s.run(&["apply", "-y"]);
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("hosts-sync"), "no warning:\n{stderr}");

    let hosts = s.hosts();
    assert!(hosts.contains("legacy.local"), "the legacy block was dropped without being asked");
    assert!(hosts.contains("new.local"));

    // А по явной команде — удаляется.
    s.ok(&["apply", "-y", "--drop-legacy"]);
    let hosts = s.hosts();
    assert!(!hosts.contains("hosts-sync"));
    assert!(!hosts.contains("legacy.local"));
    assert_system_lines_intact(&hosts);
}

#[test]
fn import_reads_legacy_hosts_files() {
    let s = Sandbox::new();
    s.init();
    let src = s.path("src");
    std::fs::create_dir_all(&src).unwrap();
    std::fs::write(
        src.join("10-local.hosts"),
        "# Local development\n127.0.0.1   k8s.orb.local\n# 127.0.0.1 *.k8s.orb.local\n",
    )
    .unwrap();
    std::fs::write(src.join("20-block.hosts"), "0.0.0.0 ads.example\n").unwrap();

    s.ok(&["import", src.to_str().unwrap()]);
    let list = s.ok(&["list", "--all"]);
    assert!(list.contains("k8s.orb.local"));
    assert!(list.contains("ads.example"));

    // Закомментированный wildcard импортирован выключенным и не мешает apply.
    s.ok(&["apply", "-y"]);
    let hosts = s.hosts();
    assert!(!hosts.contains('*'));
    assert!(hosts.contains("ads.example"));
}

#[test]
fn refuses_config_that_would_break_hosts() {
    let s = Sandbox::new();
    s.init();
    let err = s.fails(&["add", "127.0.0.1", "*.k8s.orb.local"]);
    assert!(err.contains("wildcard"), "{err}");

    let err = s.fails(&["add", "not-an-ip", "broken.local"]);
    assert!(err.contains("IP"), "{err}");
}

#[test]
fn same_hostname_on_several_ips_is_allowed() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "192.178.194.100", "analytics.google.com."]);
    s.ok(&["add", "192.178.194.101", "analytics.google.com."]);
    s.ok(&["add", "192.178.194.102", "analytics.google.com."]);

    // Точный повтор пары адрес+имя — единственное, что отвергается.
    let err = s.fails(&["add", "192.178.194.100", "analytics.google.com."]);
    assert!(err.contains("is already in group"), "{err}");

    s.ok(&["apply", "-y"]);
    let hosts = s.hosts();
    for ip in ["192.178.194.100", "192.178.194.101", "192.178.194.102"] {
        assert!(hosts.contains(ip), "lost address {ip}:\n{hosts}");
    }
    assert_eq!(
        hosts.matches("analytics.google.com.").count(),
        3,
        "there should be three lines:\n{hosts}"
    );

    // Удаление по IP снимает только его.
    s.ok(&["rm", "192.178.194.101", "--apply"]);
    let hosts = s.hosts();
    assert!(!hosts.contains("192.178.194.101"));
    assert!(hosts.contains("192.178.194.100") && hosts.contains("192.178.194.102"));

    // А по имени — все его адреса разом.
    s.ok(&["rm", "analytics.google.com.", "--apply"]);
    assert!(!s.hosts().contains("192.178.194.100"));
}

#[test]
fn one_ip_keeps_many_hostnames() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "10.0.0.7", "a.local", "b.local", "c.local"]);
    s.ok(&["apply", "-y"]);
    let hosts = s.hosts();
    assert!(
        hosts.lines().any(|l| l.starts_with("10.0.0.7") && l.ends_with("a.local b.local c.local")),
        "{hosts}"
    );

    s.ok(&["rm", "b.local", "--apply"]);
    let hosts = s.hosts();
    assert!(hosts.contains("a.local c.local"));
    assert!(!hosts.contains("b.local"));
}

#[test]
fn conflict_with_unmanaged_line_warns() {
    let s = Sandbox::new();
    s.init();
    // nas.home уже есть в файле вне блока
    s.ok(&["add", "10.0.0.99", "nas.home"]);
    let out = s.run(&["apply", "-y"]);
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("nas.home"), "no conflict warning:\n{stderr}");
    assert!(s.hosts().contains("10.0.0.5 nas.home"), "the hand-written line changed");
}

#[test]
fn groups_toggle_whole_sets() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "0.0.0.0", "ads.example", "--group", "blocklist"]);
    s.ok(&["add", "127.0.0.1", "dev.local", "--group", "local"]);
    s.ok(&["apply", "-y"]);
    assert!(s.hosts().contains("ads.example"));

    s.ok(&["group", "disable", "blocklist"]);
    s.ok(&["apply", "-y"]);
    let hosts = s.hosts();
    assert!(!hosts.contains("ads.example"));
    assert!(hosts.contains("dev.local"));

    s.ok(&["group", "enable", "blocklist", "--apply"]);
    assert!(s.hosts().contains("ads.example"));
}

#[test]
fn status_and_check_report_state() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "x.local"]);
    let status = s.ok(&["status"]);
    assert!(status.contains("apply needed"), "{status}");

    s.ok(&["apply", "-y"]);
    let status = s.ok(&["status"]);
    assert!(status.contains("matches the config"), "{status}");
    assert!(s.ok(&["check"]).contains("clean"));
}

#[test]
fn rm_removes_single_hostname_from_entry() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "a.local", "b.local"]);
    s.ok(&["rm", "b.local", "--apply"]);
    let hosts = s.hosts();
    assert!(hosts.contains("a.local"));
    assert!(!hosts.contains("b.local"));
}

#[test]
fn unwritable_target_asks_for_sudo() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "ro.local"]);
    let mut perms = std::fs::metadata(s.target()).unwrap().permissions();
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        perms.set_mode(0o444);
    }
    std::fs::set_permissions(s.target(), perms).unwrap();

    // root в CI сделает файл записываемым несмотря на права — тогда пропускаем.
    if unsafe { libc::geteuid() } == 0 {
        return;
    }
    let out = s.run(&["apply", "-y"]);
    assert!(!out.status.success());
    assert_eq!(out.status.code(), Some(4), "a permission failure has its own exit code");
    assert!(String::from_utf8_lossy(&out.stderr).contains("sudo"));
}

/// Коды выхода — часть контракта: скрипт должен отличать сломанный конфиг от
/// нехватки прав, не разбирая текст ошибки.
#[test]
fn exit_codes_tell_failures_apart() {
    let s = Sandbox::new();
    s.init();

    let usage = s.run(&["definitely-not-a-command"]);
    assert_eq!(usage.status.code(), Some(2), "clap reports a usage error");

    std::fs::write(s.path("config.yaml"), "version: 1\ngroups: [oops\n").unwrap();
    let broken = s.run(&["list"]);
    assert_eq!(broken.status.code(), Some(3), "an invalid config is a config error");

    let missing = Command::new(bin())
        .args(["--config", "/nonexistent/hostsctl/config.yaml", "list"])
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert_eq!(missing.status.code(), Some(3), "a missing config is a config error too");
}

#[test]
fn generated_docs_cover_every_command() {
    let out = Command::new(bin()).args(["docs", "cli"]).output().unwrap();
    assert!(out.status.success());
    let md = String::from_utf8_lossy(&out.stdout);
    for cmd in ["hostsctl apply", "hostsctl zone add", "hostsctl source update", "hostsctl backup"]
    {
        assert!(md.contains(&format!("`{cmd}`")), "{cmd} is missing from the reference");
    }
    // Скрытые команды в справочник не попадают: заголовка на них быть не должно.
    for hidden in ["## `hostsctl docs`", "## `hostsctl man`"] {
        assert!(!md.contains(hidden), "{hidden} should stay out of the reference");
    }

    let man = Command::new(bin()).arg("man").output().unwrap();
    assert!(man.status.success());
    let roff = String::from_utf8_lossy(&man.stdout);
    assert!(roff.contains(".TH hostsctl 1"), "the man page has no header:\n{roff}");
    assert!(roff.contains(".SH SYNOPSIS"));
}

#[test]
fn missing_config_hints_init() {
    let dir = tempfile::tempdir().unwrap();
    let out = Command::new(bin())
        .args(["--config", dir.path().join("nope.yaml").to_str().unwrap(), "list"])
        .env("NO_COLOR", "1")
        .output()
        .unwrap();
    assert!(!out.status.success());
    assert!(String::from_utf8_lossy(&out.stderr).contains("hostsctl init"));
}

#[test]
fn completions_are_generated() {
    let dir = tempfile::tempdir().unwrap();
    let out = Command::new(bin())
        .args(["--config", dir.path().join("c.yaml").to_str().unwrap(), "completions", "zsh"])
        .output()
        .unwrap();
    assert!(out.status.success());
    assert!(String::from_utf8_lossy(&out.stdout).contains("hostsctl"));
}

#[test]
fn target_stays_a_regular_file_with_same_perms() {
    let s = Sandbox::new();
    s.init();
    s.ok(&["add", "127.0.0.1", "perm.local"]);
    let before = std::fs::metadata(s.target()).unwrap();
    s.ok(&["apply", "-y"]);
    let after = std::fs::metadata(s.target()).unwrap();
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        assert_eq!(before.permissions().mode(), after.permissions().mode(), "the mode changed");
        assert_eq!(before.uid(), after.uid());
    }
    assert!(after.is_file());
    let _ = Path::new("/");
}
