//! Фрагменты документации, собранные из самого определения CLI.
//!
//! Справочник команд на сайте не пишется руками: `make gen` кладёт сюда вывод
//! `hostsctl docs cli`, а `make gen-check` роняет CI, если закоммиченная копия
//! разошлась с кодом. Так справочник не может протухнуть незаметно.

use crate::cli::{Cli, DocsCmd};
use crate::exit;
use clap::{Arg, Command, CommandFactory};

pub fn run(cmd: &DocsCmd) {
    let text = match cmd {
        DocsCmd::Cli => cli_md(),
        DocsCmd::ExitCodes => exit_codes_md(),
    };
    print!("{text}");
}

pub fn man() -> std::io::Result<()> {
    clap_mangen::Man::new(Cli::command()).render(&mut std::io::stdout())
}

const HEADER: &str =
    "<!-- Generated by `hostsctl docs cli`. Run `make gen` instead of editing this file. -->\n";

fn exit_codes_md() -> String {
    format!(
        "<!-- Generated by `hostsctl docs exit-codes`. Run `make gen` instead of editing this \
         file. -->\n\n{}",
        exit::table_md()
    )
}

fn cli_md() -> String {
    let mut root = Cli::command();
    root.build();

    let mut out = String::from(HEADER);
    out.push_str("\n## Global options\n\nThese work on every subcommand.\n\n");
    out.push_str(&arg_table(root.get_arguments().filter(|a| a.is_global_set())));

    for sub in sorted_subcommands(&root) {
        render(sub, "hostsctl", &mut out, 2);
    }
    out
}

/// Порядок в справочнике — как в `--help`, чтобы страницы читались одинаково.
fn sorted_subcommands(cmd: &Command) -> Vec<&Command> {
    cmd.get_subcommands().filter(|c| !c.is_hide_set()).collect()
}

fn render(cmd: &Command, parent: &str, out: &mut String, depth: usize) {
    let full = format!("{parent} {}", cmd.get_name());
    let children = sorted_subcommands(cmd);

    out.push_str(&format!("\n{} `{full}`\n\n", "#".repeat(depth)));

    if let Some(about) = cmd.get_long_about().or_else(|| cmd.get_about()) {
        out.push_str(&format!("{about}\n\n"));
    }

    let aliases: Vec<&str> = cmd.get_visible_aliases().collect();
    if !aliases.is_empty() {
        out.push_str(&format!("Alias: `{}`\n\n", aliases.join("`, `")));
    }

    out.push_str(&format!("```\n{}\n```\n\n", usage(cmd, &full, !children.is_empty())));

    let own = arg_table(cmd.get_arguments().filter(|a| !a.is_global_set() && !a.is_hide_set()));
    if !own.is_empty() {
        out.push_str(&own);
    }

    for child in children {
        render(child, &full, out, depth + 1);
    }
}

fn usage(cmd: &Command, full: &str, has_children: bool) -> String {
    let mut line = full.to_string();
    if has_children {
        line.push_str(" <COMMAND>");
    }
    for a in cmd.get_positionals() {
        let name = value_name(a);
        let many = a.get_num_args().is_some_and(|r| r.max_values() > 1);
        let repeat = if many { "..." } else { "" };
        if a.is_required_set() {
            line.push_str(&format!(" <{name}>{repeat}"));
        } else {
            line.push_str(&format!(" [{name}]{repeat}"));
        }
    }
    if cmd.get_arguments().any(|a| !a.is_positional() && !a.is_hide_set()) {
        line.push_str(" [OPTIONS]");
    }
    line
}

fn arg_table<'a>(args: impl Iterator<Item = &'a Arg>) -> String {
    let rows: Vec<String> = args
        .filter(|a| a.get_id() != "help" && a.get_id() != "version")
        .map(|a| {
            let mut note = a.get_help().map(|h| h.to_string()).unwrap_or_default();
            // Флагам «(default: false)» ничего не добавляет — только шумит.
            if a.get_num_args().is_some_and(|r| r.takes_values())
                && let Some(d) = a.get_default_values().first()
            {
                note.push_str(&format!(" (default: `{}`)", d.to_string_lossy()));
            }
            format!("| `{}` | {} |", signature(a), note)
        })
        .collect();

    if rows.is_empty() {
        return String::new();
    }
    format!("| Option | Description |\n| --- | --- |\n{}\n\n", rows.join("\n"))
}

fn signature(a: &Arg) -> String {
    if a.is_positional() {
        let many = a.get_num_args().is_some_and(|r| r.max_values() > 1);
        return format!("<{}>{}", value_name(a), if many { "..." } else { "" });
    }
    let mut s = String::new();
    if let Some(c) = a.get_short() {
        s.push_str(&format!("-{c}, "));
    }
    if let Some(l) = a.get_long() {
        s.push_str(&format!("--{l}"));
    }
    if a.get_num_args().is_some_and(|r| r.takes_values()) {
        s.push_str(&format!(" <{}>", value_name(a)));
    }
    s
}

fn value_name(a: &Arg) -> String {
    if let Some(names) = a.get_value_names()
        && let Some(first) = names.first()
    {
        return first.to_string();
    }
    a.get_id().as_str().to_uppercase()
}
