//! Сборка управляемого блока из конфига.

use crate::config::{Config, Group};
use crate::hostsfile::{BEGIN, END, HostsFile};
use crate::remote;
use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;

pub struct Rendered {
    pub block: Vec<String>,
    pub warnings: Vec<String>,
    pub hosts_count: usize,
    pub groups_used: usize,
}

/// Ширина колонки IP, чтобы имена выстраивались в столбик. Дальше не выравниваем —
/// у IPv6 длина непредсказуемая, а огромные блоклисты от этого только пухнут.
const IP_COL: usize = 15;

/// Начало строки со временем генерации — по нему её потом узнаём.
pub const GENERATED_PREFIX: &str = "# generated by hostsctl ";

/// Оставляет старую отметку времени, если больше ничего не изменилось.
///
/// Иначе `diff` показывал бы изменение каждую минуту, `status` вечно требовал
/// apply, а сам apply переписывал бы `/etc/hosts` и плодил бэкапы на пустом
/// месте. Заодно отметка начинает означать то, что от неё и ждут: когда блок
/// менялся в последний раз.
pub fn preserve_timestamp(old: &str, new: String) -> String {
    let find = |s: &str| s.lines().find(|l| l.starts_with(GENERATED_PREFIX)).map(str::to_string);
    let (Some(old_line), Some(new_line)) = (find(old), find(&new)) else {
        return new;
    };
    if old_line == new_line {
        return new;
    }
    let candidate = new.replacen(&new_line, &old_line, 1);
    if candidate == old { candidate } else { new }
}

pub fn render(
    cfg: &Config,
    cache_dir: &Path,
    generated_at: &str,
    config_path: &Path,
) -> Result<Rendered> {
    let mut block = vec![
        BEGIN.to_string(),
        format!("{GENERATED_PREFIX}{generated_at}"),
        format!("# source: {} — edit that, not this block", config_path.display()),
    ];
    let mut warnings = vec![];
    let mut hosts_count = 0usize;
    let mut groups_used = 0usize;
    let mut seen = Seen::default();

    for g in cfg.groups.iter().filter(|g| g.enabled) {
        let lines = match group_lines(g, cache_dir, &mut warnings, &mut seen) {
            Ok(Some(l)) => l,
            Ok(None) => continue,
            Err(e) => {
                warnings.push(format!("group '{}': {e}", g.name));
                continue;
            }
        };
        if lines.is_empty() {
            continue;
        }
        groups_used += 1;
        hosts_count += lines.len();
        block.push(String::new());
        block.push(header(g));
        block.extend(lines);
    }

    block.push(END.to_string());
    Ok(Rendered { block, warnings, hosts_count, groups_used })
}

fn header(g: &Group) -> String {
    match (&g.description, &g.source) {
        (Some(d), _) => format!("# --- {} — {d} ---", g.name),
        (None, Some(s)) => format!("# --- {} — {} ---", g.name, s.url),
        (None, None) => format!("# --- {} ---", g.name),
    }
}

/// Что уже отрендерено. Пара «адрес + имя» уникальна, само имя — нет:
/// одно имя на нескольких адресах — это нормальные несколько A-записей.
#[derive(Default)]
struct Seen {
    pairs: std::collections::HashSet<(String, String)>,
    /// имя хоста -> группа, которая объявила его первой
    owner: HashMap<String, String>,
}

/// `Ok(None)` — группу нужно пропустить (например, кеш удалённого списка пуст).
fn group_lines(
    g: &Group,
    cache_dir: &Path,
    warnings: &mut Vec<String>,
    seen: &mut Seen,
) -> Result<Option<Vec<String>>> {
    let mut out = vec![];

    if let Some(src) = &g.source {
        let Some(entries) = remote::cached_entries(&g.name, src, cache_dir)? else {
            warnings.push(format!(
                "group '{}': the remote list is not cached — run hostsctl source update {}",
                g.name, g.name
            ));
            return Ok(None);
        };
        for (ip, host) in entries {
            out.extend(entry_lines(&g.name, &[ip], &[host], None, warnings, seen));
        }
        return Ok(Some(out));
    }

    for e in g.entries.iter().filter(|e| e.enabled) {
        out.extend(entry_lines(
            &g.name,
            &e.ips,
            &e.hostnames,
            e.comment.as_deref(),
            warnings,
            seen,
        ));
    }
    Ok(Some(out))
}

/// Строка на каждый адрес записи. Ничего не выбрасываем, кроме точных повторов
/// пары «адрес + имя» — они в hosts не значат ничего.
fn entry_lines(
    group: &str,
    ips: &[String],
    hostnames: &[String],
    comment: Option<&str>,
    warnings: &mut Vec<String>,
    seen: &mut Seen,
) -> Vec<String> {
    let mut out = vec![];
    for ip in ips {
        let mut names = vec![];
        for h in hostnames {
            let key = h.trim_end_matches('.').to_lowercase();
            if !seen.pairs.insert((ip.clone(), key.clone())) {
                warnings.push(format!("'{ip} {h}' appears twice — the duplicate was dropped"));
                continue;
            }
            match seen.owner.get(&key) {
                Some(prev) if prev != group => warnings.push(format!(
                    "'{h}' is declared in group '{prev}' and in '{group}' — \
                     check that several addresses for one name are intended here"
                )),
                Some(_) => {}
                None => {
                    seen.owner.insert(key, group.to_string());
                }
            }
            names.push(h.clone());
        }
        if names.is_empty() {
            continue;
        }
        out.push(one_line(ip, &names, comment));
    }
    out
}

fn one_line(ip: &str, names: &[String], comment: Option<&str>) -> String {
    let pad = IP_COL.saturating_sub(ip.len()).max(1);
    let mut line = format!("{ip}{}{}", " ".repeat(pad), names.join(" "));
    if let Some(c) = comment {
        line.push_str(&format!("  # {c}"));
    }
    line
}

/// Предупреждения о конфликтах с тем, что лежит в файле вне нашего блока.
pub fn conflicts_with_unmanaged(file: &HostsFile, block: &[String]) -> Vec<String> {
    // имя -> все адреса, которые мы для него выдаём
    let mut ours: HashMap<String, Vec<String>> = HashMap::new();
    for h in block.iter().filter_map(|l| crate::hostsfile::parse_line(l)) {
        for n in h.hostnames {
            ours.entry(n.trim_end_matches('.').to_lowercase()).or_default().push(h.ip.clone());
        }
    }

    let mut out = vec![];
    for (lineno, h) in file.unmanaged_lines() {
        for name in &h.hostnames {
            let key = name.trim_end_matches('.').to_lowercase();
            if let Some(our_ips) = ours.get(&key)
                && !our_ips.contains(&h.ip)
            {
                out.push(format!(
                    "'{name}' also appears in {} on line {lineno} as {} — that line is outside the \
                     managed block, hostsctl leaves it alone",
                    file.path.display(),
                    h.ip
                ));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Entry, Group};

    fn cfg_with(groups: Vec<Group>) -> Config {
        Config { version: 1, settings: Default::default(), include: None, groups }
    }

    fn group(name: &str, entries: Vec<Entry>) -> Group {
        let mut g = Group::new(name);
        g.entries = entries;
        g
    }

    #[test]
    fn renders_enabled_entries_only() {
        let mut off = Entry::new("10.0.0.2", vec!["off.local".into()]);
        off.enabled = false;
        let cfg = cfg_with(vec![group(
            "local",
            vec![Entry::new("127.0.0.1", vec!["a.local".into()]), off],
        )]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        let text = r.block.join("\n");
        assert!(text.contains("a.local"));
        assert!(!text.contains("off.local"));
        assert_eq!(r.hosts_count, 1);
    }

    #[test]
    fn disabled_group_is_skipped() {
        let mut g = group("blocked", vec![Entry::new("0.0.0.0", vec!["ads.example".into()])]);
        g.enabled = false;
        let cfg = cfg_with(vec![g]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        assert!(!r.block.join("\n").contains("ads.example"));
    }

    #[test]
    fn same_hostname_in_two_groups_is_kept_and_warned() {
        let cfg = cfg_with(vec![
            group("one", vec![Entry::new("1.1.1.1", vec!["dup.local".into()])]),
            group("two", vec![Entry::new("2.2.2.2", vec!["dup.local".into()])]),
        ]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        let text = r.block.join("\n");
        assert!(text.contains("1.1.1.1"), "the first line went missing");
        assert!(text.contains("2.2.2.2"), "the second line was dropped — that was the bug");
        assert_eq!(r.warnings.len(), 1, "it still has to warn");
    }

    #[test]
    fn one_hostname_on_many_ips_renders_every_line() {
        let mut e = Entry::new("192.178.194.100", vec!["analytics.google.com.".into()]);
        e.ips.push("192.178.194.101".into());
        e.ips.push("192.178.194.102".into());
        let cfg = cfg_with(vec![group("blocklist", vec![e])]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        let text = r.block.join("\n");
        for ip in ["192.178.194.100", "192.178.194.101", "192.178.194.102"] {
            assert!(text.contains(ip), "lost address {ip}:\n{text}");
        }
        assert_eq!(r.hosts_count, 3);
        assert!(r.warnings.is_empty(), "within one group this is fine: {:?}", r.warnings);
    }

    #[test]
    fn exact_duplicate_pair_is_dropped_once() {
        let cfg = cfg_with(vec![group(
            "g",
            vec![
                Entry::new("1.1.1.1", vec!["x.local".into()]),
                Entry::new("1.1.1.1", vec!["x.local".into()]),
            ],
        )]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        assert_eq!(r.hosts_count, 1);
        assert_eq!(r.warnings.len(), 1);
    }

    fn with_stamp(stamp: &str, body: &str) -> String {
        format!("127.0.0.1 localhost\n{BEGIN}\n{GENERATED_PREFIX}{stamp}\n{body}\n{END}\n")
    }

    #[test]
    fn timestamp_alone_is_not_a_change() {
        let old = with_stamp("2026-08-10 22:07", "1.1.1.1 a");
        let new = with_stamp("2026-08-11 11:43", "1.1.1.1 a");
        assert_eq!(
            preserve_timestamp(&old, new),
            old,
            "only the timestamp changed — no reason to touch the file"
        );
    }

    #[test]
    fn timestamp_updates_when_content_changes() {
        let old = with_stamp("2026-08-10 22:07", "1.1.1.1 a");
        let new = with_stamp("2026-08-11 11:43", "2.2.2.2 b");
        let out = preserve_timestamp(&old, new);
        assert!(out.contains("2026-08-11 11:43"), "the new timestamp was lost: {out}");
        assert!(out.contains("2.2.2.2 b"));
    }

    #[test]
    fn block_is_marker_wrapped() {
        let cfg = cfg_with(vec![group("l", vec![Entry::new("127.0.0.1", vec!["x".into()])])]);
        let r = render(&cfg, Path::new("/nonexistent"), "now", Path::new("/c.yaml")).unwrap();
        assert_eq!(r.block.first().unwrap(), BEGIN);
        assert_eq!(r.block.last().unwrap(), END);
    }
}
