# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/release.yml in
# jtprogru/hostsctl. Do not edit by hand.
class Hostsctl < Formula
  desc "Manage /etc/hosts from a YAML config: groups, zone files, blocklists, backups"
  homepage "https://jtprogru.github.io/hostsctl/"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jtprogru/hostsctl/releases/download/v${VERSION}/hostsctl-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_AARCH64_DARWIN}"
    else
      url "https://github.com/jtprogru/hostsctl/releases/download/v${VERSION}/hostsctl-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_X86_64_DARWIN}"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtprogru/hostsctl/releases/download/v${VERSION}/hostsctl-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_AARCH64_LINUX}"
    else
      url "https://github.com/jtprogru/hostsctl/releases/download/v${VERSION}/hostsctl-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_X86_64_LINUX}"
    end
  end

  def install
    bin.install "hostsctl"
    man1.install "man/hostsctl.1" if File.exist?("man/hostsctl.1")
    if File.directory?("completions")
      bash_completion.install "completions/hostsctl.bash" => "hostsctl"
      zsh_completion.install "completions/hostsctl.zsh" => "_hostsctl"
      fish_completion.install "completions/hostsctl.fish"
    end
  end

  def caveats
    <<~EOS
      Commands that write to /etc/hosts (apply, off, backup restore) need root:

        sudo hostsctl apply

      Everything else — list, diff, status, check — runs as your own user.
    EOS
  end

  test do
    system bin/"hostsctl", "--version"

    # A full round trip against a throwaway hosts file: the real /etc/hosts is
    # never touched, and a broken binary fails here rather than on a user's box.
    (testpath/"hosts").write "127.0.0.1\tlocalhost\n"
    args = ["--config", testpath/"config.yaml", "--target", testpath/"hosts"]
    system bin/"hostsctl", *args, "init"
    system bin/"hostsctl", *args, "add", "127.0.0.1", "brew.test"
    system bin/"hostsctl", *args, "apply", "-y"
    assert_match "brew.test", (testpath/"hosts").read
    assert_match "localhost", (testpath/"hosts").read
  end
end
